import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Provider from '@/components/Provider'
import { Providers } from './redux/provider'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Provider>
            <main>
              <Header />
              {children}  
            </main>
          </Provider>
        </Providers>

      </body>
    </html>
  )
}
